apiVersion: apps/v1
kind: Deployment                               # type of Kubernetes build or creation
metadata:
  name: django-argocd-app-deployment        # name of the kubernetes deployment
  labels:
    app: django-argocd-app                  # name of the label you want to give your created pods
spec:
  replicas: 3                                  # number of pods to create
  selector:
    matchLabels:
      app: django-argocd-app                # use the name of the label as the selector
  template:
    metadata:
      labels:
        app: django-argocd-app              # this tags every created pod with django-argocd-app tag
    spec:
      containers:
      - name: django-argocd-application            # the container name for the created django
        image: edunaking/portfolio-website:41f66d0

        # imagePullPolicy: Never              # this tells kubernetes to use the image provided locally in your terminal 
                                            # instead of pulling directly from docker hub. if you want to pull from 
                                            # docker hub, then comment image pull policy 
                                                        
        ports:                                
        - containerPort: 8000        # use the port your django app is listening on
                                     # inspect your Dockerfile to see the port number
                                     # django listens on port 8000
