name: Deploy to Argo CD

on:
  push:
    branches: [main]                 # for every push to the main branch 
                                     # deploy new changes to argo cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # automatically logs you in to docker hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # executes the deploy.sh script
      - name: Run deploy script
        run: |
          chmod +x deploy.sh               
          ./deploy.sh